version: 2.1

jobs:
    build:
      steps:
        - checkout
        - run:
            name: Build pytorch serve
            command: python setup.py bdist_wheel --release --universal

workflows:
  version: 2
  smoke:
    jobs:
      - build
