version: 2.1

jobs:
    build:
      docker:
        - image: prashantsail/pytorch-serve-build
      steps:
        - checkout
        - run:
            name: Build pytorch serve
            command: python setup.py bdist_wheel --release --universal
        - store_artifacts:
            name: Store gradle testng results
            path: frontend/server/build/reports/tests/test


workflows:
  version: 2
  smoke:
    jobs:
      - build
